name: Build DEMAI

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize]

jobs:
  contract:
    name: Contract CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - name: Install deps
        run: pnpm install

      - name: Contract - compile
        run: pnpm compile
        working-directory: packages/contract

      - name: Contract - test
        run: pnpm test
        working-directory: packages/contract

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    needs: contract

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - name: Install deps
        run: pnpm install

      - name: Frontend - build
        run: pnpm build
        working-directory: apps/frontend
